export enum EmailTemplateType {
	INQUIRY_RESPONSE = "INQUIRY_RESPONSE",
	PASSWORD_RESET = "PASSWORD_RESET",
	LOGIN_ALERT = "LOGIN_ALERT",
	STUDENT_MESSAGE = "STUDENT_MESSAGE",
	NEW_USER_REGISTER = "NEW_USER_REGISTER",
	OTHERS = "OTHERS",
}
